# Generated by Django 2.2.9 on 2020-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='hgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
